apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 30m
  releaseName: longhorn
  chart:
    spec:
      chart: longhorn
      version: 1.8.2
      sourceRef:
        kind: HelmRepository
        name: longhorn
      interval: 30m
  targetNamespace: longhorn-system
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  values:
    defaultSettings:
      defaultDataPath: "/storage1"
      defaultReplicaCount: "1"
    persistence:
      defaultClassReplicaCount: "1"
    ingress:
      enabled: true
      ingressClassName: traefik
      host: longhorn.homelab.local
    
