apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: librespeed
spec:
  interval: 30m
  releaseName: librespeed
  chart:
    spec:
      chart: app-template
      version: 4.1.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-labs
        namespace: librespeed
      interval: 30m
  targetNamespace: librespeed
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  values:
    fullnameOverride: librespeed
    defaultPodOptions:
      securityContext:
        # https://github.com/librespeed/speedtest/issues/663
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault
    controllers:
      librespeed:
        strategy: RollingUpdate
        containers:
          librespeed:
            image:
              repository: ghcr.io/librespeed/speedtest
              tag: 5.4.1@sha256:0e0d9c8c2e5aa362164cf0bf25a48a606b5701f6bc7fa1695975b687aaec26a9
            env:
              MODE: standalone
              WEBPORT: 8080
            securityContext:
              allowPrivilegeEscalation: false
              # cp: cannot create regular file '/var/www/html/speedtest.js': Read-only file system
              readOnlyRootFilesystem: false
              #+ chown -R www-data /var/www/html/backend /var/www/html/favicon.ico /var/www/html/index.php /var/www/html/speedtest.js /var/www/html/speedtest_worker.js
              #capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
              limits:
                memory: 100Mi
    service:
      librespeed:
        controller: librespeed
        ports:
          http:
            port: 8080
    ingress:
      librespeed:
        enabled: true
        className: tailscale
        hosts:
          - host: speed
            paths:
              - path: /
                service:
                  identifier: librespeed
                  port: http
