apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
    name: alert-config-telegram
    namespace: monitoring
    labels:
        alertmanagerConfig: alertmanager-telegram
spec:
    route:
        groupBy:
            - alertname
            - job
            - namespace
        groupWait: 30s
        groupInterval: 5m
        repeatInterval: 1h
        receiver: telegram
        routes:
            - receiver: telegram
              matchers:
                - name: severity
                  matchType: =~
                  value: warning|critical
    receivers:
        - name: telegram
          telegramConfigs:
            - botToken:
                name: telegram-bot-token-secret
                key: bot-token
              chatID: ENC[AES256_GCM,data:pSMQ7W1vfY1DYS8=,iv:i1B0kczhmNiDYC/j7Ssksjn3c4AYAy7zIKlqPVqOMs8=,tag:uOPIyxXURdaFVNISXrbaRg==,type:int]
              parseMode: MarkdownV2
              disableNotifications: false
              sendResolved: true
sops:
    age:
        - recipient: age185tgcntd96x8y5kjse7w5snnq3ml37pzvtjnrmqudw9dxsa8p99q9xmq5v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArekUxcXlZZ1dWNnRsQkc2
            a1poazVucXZ6ZDJGK3lUZ3FrUzRodDBVbkE0CmZ4QTlXQ0JHa0o2WHpnc3BaU0hU
            MkNTM0tuVlllTjhReXBUeVVqWHoyeGcKLS0tIEx6Z0hqby82VzdpcllrSXhSMG5a
            V1VJc3UwSUEwbUxZcjYyL2VHRVo4NUUKjXgLUz+F+rGxOVhQedFgZcN1RH8MLEho
            z7iciPk4fLXytlXUM/i0VIUtrMqKPvtSTp3y1iQGCBUEUIPMw+yYog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T18:11:31Z"
    mac: ENC[AES256_GCM,data:UXRlkgW0ic5J4Shr9uMdghmhVp2oNq2sgd82E8CQwHqp8PHcWEwMtWIwCmof2kLUz4ONTCEPPPFtnQstOHkm0sJpf5cFetuiwZwyWEBR8LG1xt5tI0EQ8+9J4q1UeJiBg+GK+JuAoFVosQ+thmAEh2kRRtz7Zt82iCm+x4IDqvc=,iv:ociOzJ/bvKgNPBYGFle1NdMff7K0ZrGHB9zNig+eE1s=,tag:L6yYR1E7OK3CD6X+fsighg==,type:str]
    encrypted_regex: ^chatID$
    version: 3.10.2
